# Generated by Django 5.0.6 on 2024-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
