# Generated by Django 5.0.6 on 2024-07-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, default='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, default='country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='number',
            field=models.CharField(blank=True, default='number', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='postal_code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, default='state', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(blank=True, default='street_address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, default='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(blank=True, default='number', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='postal_code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, default='state', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_address',
            field=models.CharField(blank=True, default='street_address', max_length=255, null=True),
        ),
    ]
