# Generated by Django 5.0.6 on 2024-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(help_text='Small title above main title', max_length=255)),
                ('title_large', models.CharField(help_text='Main large title', max_length=255)),
                ('title_brand', models.CharField(help_text='Brand title', max_length=255)),
                ('description', models.TextField(help_text='Description under the titles')),
                ('button_text', models.CharField(help_text='Text displayed on the button', max_length=100)),
                ('button_link', models.URLField(help_text='URL that the button links to')),
                ('image', models.ImageField(help_text='Image for the slider', upload_to='hero_slider/')),
            ],
        ),
    ]
