# Generated by Django 5.0.6 on 2024-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_check_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
