# Generated by Django 5.0.6 on 2024-07-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_check_out', '0002_cartitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
