# Generated by Django 5.0.6 on 2024-08-01 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Dashboard', '0002_alter_billingaddress_city_and_more'),
        ('Product', '0004_product_show_rating'),
        ('cart_and_check_out', '0004_cartitem_added_at_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder_confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account_Dashboard.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='oder_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('oder_confirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_and_check_out.oder_confirm')),
            ],
        ),
    ]
