# Generated by Django 5.0.6 on 2024-08-01 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Dashboard', '0002_alter_billingaddress_city_and_more'),
        ('Product', '0004_product_show_rating'),
        ('cart_and_check_out', '0005_oder_confirm_oder_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oder_product',
            new_name='OrderProduct',
        ),
        migrations.CreateModel(
            name='OrderConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Dashboard.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='oder_confirm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_and_check_out.orderconfirm'),
        ),
        migrations.DeleteModel(
            name='Oder_confirm',
        ),
    ]
