# Generated by Django 5.0.6 on 2024-08-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_check_out', '0006_rename_oder_product_orderproduct_orderconfirm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='oder_confirm',
            new_name='order_confirm',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
