# Generated by Django 5.0.6 on 2024-08-01 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_check_out', '0007_rename_oder_confirm_orderproduct_order_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirm',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
